# Generated by Django 5.0.6 on 2024-07-01 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulding', '0003_remove_house_available_remove_house_not_fully_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='flour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='bulding.flour'),
        ),
        migrations.AlterField(
            model_name='house',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='bulding.block'),
        ),
    ]
