# Generated by Django 5.0.6 on 2024-07-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulding', '0004_alter_block_flour_alter_house_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='buyer',
        ),
        migrations.AddField(
            model_name='house',
            name='buyer_first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='buyer_last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='buyer_phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='buyer_spend',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='how_much_is_left',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='num_in_block',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
