# Generated by Django 5.0.6 on 2024-07-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulding', '0005_remove_house_buyer_house_buyer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='buyer_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='buyer_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='buyer_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='number',
            field=models.CharField(unique=True),
        ),
    ]
